sudo: true
dist: xenial
services:
  - docker
language: python
python:
  - '3.7'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --upload --pdf SCTR-21.pdf --lsstdoc SCTR-21.tex --env=travis --ltd-product sctr-21"
env:
  global:
    - secure: "vP7bEv2UNFb2eku/fD/9DAQR8SHE7WSu1PZWX7grbsJTWpvElwQyDcDDkfrBzRjRUzvc6YCKXewG10tPpJVm0H9uzM0kxdj8hbSY/CKZxwy8jBHLiUj8Uns9q0jxDi02zIFtiPXj002CnqpQ1O6SxrMztLoGI5REAEF1cWr+eiZeP0jRDbLnYbMaerrILLuwlceJ2zbVheo4lH1rYU2YVFSNZ+xAPHhzhhVetw23XT3Ea+8G0sp626b1jUgWr+/Lh63yo1rABOyeRTzrtygn21grQIFK/YmzTmMZHkO/v+aiFc6e5eJF2aErSIGSYEijDUZ4jTuPTA0vTLUBVhaXF4m4jHtyJYDNYrRpRjLffR+5Vv4rA/m+gD5frThgO6oZIqAMxWHvRenaZi1zbRfgkAosxXrzTl9yx9fXLdJhhXhXf+KcuyMmZtNvGsCwiVy3Kqef1LPEOGVVVJBJ3Ws4Q95keh2psfAMl9SOgVnW+jruZ3ObOTVMszczgALtTpoI5pDZT3v+0i/QN7XvwTuZopFhKEhRqB/RJH9r7L/K3ihLPOAsMGjgwr0TZctX53KalY3BoRcMKfjHwPhxy0obccH6rkNJQAM4GiyTRzXqVkjYaasW/jmaXA2Q86SIFdrvnmzKqx/iSK2m/9ak2Bf/9gHK93qofX/VV+gYdf4B9rk="
    - secure: "JsCbMWnCqxCpHTjoqHVzoj0YglyM0l7Alkt4pYAmy7cBamqYhY8g401HQ48Y+lg1lHg5Or2/wa5jV4Bfy+JaXAnmPwlffliuWR6DaDbjqjGew0UpVATPtlbD1tw9DvL7UCyAElbKaa4L+BuZmNZz0qlvNjXDUtcyPDAGJSmwkY/jB7N4dEaqrZVb/kYvWA51exlqPvHl6wp4QZTsX1q+vjTMFhSgpf14X/1JjmCo0IMqBr0ybBJ7IV5zhNn41I6npBK3Bw4unggulIxgAoXMNHnd9rszeUKqGl0Op2zwyf8xZi0EzLVAy7LVMdU0MiS9mMAcOcMx3sBNGEvgN43fZOa8aPouOQqBqc8Uw5P0woxG6kHAENOyUcgsh8Hhq04SRRrs9iv1m7DP1vR/s7045DXseGv6PCTkDCZRfyXwSHOBLqGacAqyM4PtD5+hOtSLtT3hvevAOKO9fAsqa+6m78St38n5i7t9KaDfIjLBE7shpwDiuBP979BQM4eCFZVjra+dhUgiAWp9iwYGQw1wiwbCh0QjKcn0KRW+xMFhdUvqRGhhH3ZxBdgu3LweI+cG6KMmJLmQyhbgWAe/ztjeaoc5yl4/rxvbOYsDEmuFzuTlkC1T5dIhe3Ogg5LMoTkh2WPvV6dQsniF0iIlaUxmyLAvwHr9MwzskyUxycaGQIQ="
